### ISSUE TITLE
Mark unavailable products

### ISSUE THREAD

**Issue by dArignac** [ponyriders/django-amazon-price-monitor#14]
If a product is not available, there is no price created upon the task run. Somehow we should mark the product as currently not available.
Sample product: http://www.amazon.de/gp/product/B003Y3VWGQ/

**Comment by dArignac** [comment]
How is this done in the angular-frontend branch? In current master it says that there is no price available which is sufficient.

**Comment by mmrose** [comment]
This is not handled at the moment.

**Comment by mmrose** [comment]
Suggestion: As there is now a foreign key pointing to the current price, setting this value empty would lead to an empty value in the API and therefore an empty value in the frontend indicating that there was no syncronized value
