### ISSUE TITLE
Don't be able to add a subscription for a product more than once

### ISSUE THREAD

**Issue by dArignac** [ponyriders/django-amazon-price-monitor#20]
Currently you can add x subscriptions for the same product (and email notification).
With the subscription remove fix in e392107e60c1e185790ec61b77326474a14b221f this will throw an error in the frontend.
Generally one should only be able to create a subscription for a product and notification email once, this is currently not secured.

**Comment by dArignac** [comment]
It should not work this way. The better approach is to allow multiple subscriptions and e.g. notify in frontend if a subscription with the current value already exists.

**Comment by mmrose** [comment]
The angular branch will be aware of multiple subscriptions for a product. They will be shown on a product detail page at the moment and also subscriptions with the same value are accepted, but not created a second time.

**Comment by dArignac** [comment]
Great, so I assign this ticket to you and we close it after the angular branch was tested and reintegrated.

**Comment by mmrose** [comment]
This is done in angular frontend
