### ISSUE TITLE
Show highest and lowest price ever

### ISSUE THREAD

**Issue by dArignac** [ponyriders/django-amazon-price-monitor#25]
Would be nice to see the highest and lowest price for a product ever.

**Comment by dArignac** [comment]
Should also display the date of the high/low.

**Comment by mmrose** [comment]
There is naive implementation of this available in the Product serialization, but this causes slow and to many queries on the database.
A more performant, but less clean approach would be to store this data directly on the product, but then the product would get 6 more fields (value/currency/date seen for both min and max)

**Comment by dArignac** [comment]
We should measure if attaching the high/low prices via foreign key is an alternative. From a data structural point of view, adding this 6 fields is not rellay good design.

**Comment by mmrose** [comment]
Measurements showed, that attaching high/low/current prices via foreign keys is much faster than filtering in the price_set attribute. 
This is not a very nice model structure, but the performance improvements are more important.
Highest and lowest price are now shown on detail page.
