### ISSUE TITLE
Limit graphs

### ISSUE THREAD

**Issue by dArignac** [ponyriders/django-amazon-price-monitor#26]
AFAIK the graph shows all prices the product has. If the product is there for a very long time, then there is a huge amount of data to be loaded and displayed. We should think about limiting this graph to a certain time slice (e.g. the last month) and add the option to change the displayed time slice.

**Comment by dArignac** [comment]
Within angular-frontend the graphs are images, so the issue with the amount of data in the browser is solved. Can we already change the displayed date range?

**Comment by mmrose** [comment]
With the angular frontend, the graphs are now limited in data amount
