### ISSUE TITLE
Endless synchronization queue

### ISSUE THREAD

**Issue by dArignac** [ponyriders/django-amazon-price-monitor#38]
We have a funny endless queue phenomenom here: the sync all products task runs every 5 minutes. A taskrun queries 10 products and if there are more products, the task will be run again after 10 seconds. If there are more than 300 products to sync, the periodic task will run before the actual sync run is done. This stacks up a pile of queues.

**Comment by mmrose** [comment]
Maybe [rate limiting on the celery task](http://docs.celeryproject.org/en/latest/userguide/tasks.html#Task.rate_limit) is a solution.

**Comment by dArignac** [comment]
Additionally we run into request limitations here.
The formula for how many request are allowed per second is

```1 + round ([last 30 days shipped Sales])/$4,600)```

(from: https://affiliate-program.amazon.com/gp/advertising/api/detail/faq.html)

Sales depend on the used Amazon account. To be safe here, there should be only one request per second. Within a single request we can use up to 10 products (see http://docs.aws.amazon.com/AWSECommerceService/latest/DG/PerformingMultipleItemLookupsinOneRequest.html).

**Comment by dArignac** [comment]
I rewrote the whole product api task thing. We do not use periodic tasks anymore. Workflow is documented in readme, too.
