### ISSUE TITLE
Sync on product creation not working

### ISSUE THREAD

**Issue by mmrose** [ponyriders/django-amazon-price-monitor#55]
Products created via Angular and normal view are not synced immediately after creation.

The syncronization is trigger via a post_save signal handler. This handler triggers SynchronizeSingleProductTask wih the ASIN of the new created product. 
It is a very common problem, that the post_save signal handler also runs inside the transaction, that creates the product at the end, so the task is triggered just before the product is actually is created in the database.

**Comment by dArignac** [comment]
I was only able to reproduce this on the angular view.

**Comment by dArignac** [comment]
The logs says the following:

```
ERROR 2015-07-26 16:35:58,312 tasks.py 152 Product with ASIN B00SU7H288 could not be found.
INFO 2015-07-26 16:35:58,313 tasks.py 157 Synchronizing products with ItemIds 
INFO 2015-07-26 16:35:58,313 api.py 112 starting lookup for ASINs 
ERROR 2015-07-26 16:35:58,410 api.py 174 Request for item lookup (ResponseGroup: Large, ASINs: ) was not valid
```
