### ISSUE TITLE
Graphs do not render correct values

### ISSUE THREAD

**Issue by dArignac** [ponyriders/django-amazon-price-monitor#60]
The graphs may not render the correct values (I'm not 100% sure), but for sure the current value is not displayed. Additionally there is no legend for the x axis.

See the examples below and their current value, which is not displayed correctly:

![pm1](https://cloud.githubusercontent.com/assets/106409/9699245/ac4833bc-53db-11e5-8801-44cb3a09b24d.png)
![pm2](https://cloud.githubusercontent.com/assets/106409/9699247/adc1c140-53db-11e5-81f3-db59405023e7.png)

**Comment by mmrose** [comment]
Added x axis labels to charts on detail page, but could not manage to show a custom amount of labels. Also the values in the chart were correct, but the most recent value was on the left side, not on the right. Fixed this, too.

**Comment by dArignac** [comment]
![auswahl_003](https://cloud.githubusercontent.com/assets/106409/9856595/f03aa7ee-5b15-11e5-9f83-19d75cf8c986.png)

Can we style the x axis legend to be more readable? Currently the values are cut off.

**Comment by mmrose** [comment]
Fixed that.
