### ISSUE TITLE
Improve product addition in frontend

### ISSUE THREAD

**Issue by dArignac** [ponyriders/django-amazon-price-monitor#79]
In the frontend you currently have to enter the following values to add a product:

* ASIN (ok)
* E-Mail (not so good)
* Price (ok)

![image](https://cloud.githubusercontent.com/assets/106409/11761503/b60b7a80-a0c5-11e5-8497-f5bbb88e9233.png)

The email is the model EmailNotification. I guess usually a user will only have one email, but it may happen he/she has more than one. In the frontend you always have to enter the fuill email (through browser autocompletion it is ok, but this does not work on mobile (at least for me)) and this is annoying. 

In the old frontend one could select the emails from a dropdown with an email set as default value. Would be nice to have this in the frontend again.
Maybe we can add a sorting property to the email so the dropdown is filled in this order.

**Comment by mmrose** [comment]
Added a dropdown solution in #104
