### ISSUE TITLE
Implement a full-usable frontend

### ISSUE THREAD

**Issue by dArignac** [ponyriders/django-amazon-price-monitor#8]
Please do so ;-)

**Comment by mmrose** [comment]
Angular-Frontend is near a usable state. At the moment subscriptions on product detail page are not filtered by user.

**Comment by dArignac** [comment]
One more thing... ;)
The image urls are HTTP by default. But we have a setting PRICE_MONITOR_IMAGES_USE_SSL to enforce them via HTTPS. I can't remember how we solved this in the "old" master, there is this Product.__get_image_url method that changes the image host to HTTPS if configured but it was nowhere used. I added a method Product.get_image_urls to get all image URLs with correct schema for use in the old frontend, see https://github.com/ponyriders/django-amazon-price-monitor/commit/f247f543898f84be18d9dfaed9a03959903dc988. This has to be adapted for the angular frontend somehow.

**Comment by mmrose** [comment]
It uses the properties again as this plays nicely together with serialization of DRF. I'm looking into that.

**Comment by mmrose** [comment]
I would close this, as it is implemented and the rest should be done via new features or bugs, do you agree @darignac ?

**Comment by dArignac** [comment]
Agreed.
