### ISSUE TITLE
Graphs show wrong date range

### ISSUE THREAD

**Issue by dArignac** [ponyriders/django-amazon-price-monitor#90]
The graphs do not reflect the current date, there somewhere back in time. They should show the current price at the right and some days/weeks before (not the whole history).

![alhe_000387](https://cloud.githubusercontent.com/assets/106409/12176671/cebf817c-b568-11e5-9275-d4e5e874d927.png)

**Comment by dArignac** [comment]
partly fixed in #97

**Comment by mmrose** [comment]
Should I have a look at it?

**Comment by dArignac** [comment]
I'm on it.
